export interface DemoStep {
  targetType: 'load-report' | 'select-scenario' | 'fill-input' | 'click-suggestion' | 'info';
  targetNodeType?: string;
  targetVariable?: string;
  suggestionId?: string;
  expectedValue?: number;
  tolerance?: number; // fraction, e.g. 0.05 = 5%
  message: string;
  highlightTarget?: 'report-panel' | 'node-input' | 'node-suggestion' | 'scenario-card';
  scenarioCardIndex?: number;
}

export interface DemoScenario {
  id: number;
  title: string;
  enunciado: string;
  color: string; // tailwind bg class
  accentColor: string; // hex for pulse
  steps: DemoStep[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 1,
    title: 'Operación Óptima',
    enunciado: 'La empresa busca optimizar su producción. Con una capacidad de 263,420 unidades, se ha decidido operar al 80% de capacidad (aprox. 210,000 unidades). Calcula el Costo Total de Producción y el Costo Unitario bajo estas condiciones.',
    color: 'bg-emerald-500',
    accentColor: '#10b981',
    steps: [
      {
        targetType: 'fill-input',
        targetNodeType: 'production_target',
        targetVariable: 'target',
        expectedValue: 210000,
        tolerance: 0.01,
        message: 'Escribe 210,000 en "Unidades Objetivo". Operaremos al 80% de capacidad.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'production_target',
        suggestionId: 'material_needs',
        message: 'Haz clic en "+ Calcular Materia Prima" para crear el nodo de requerimientos.',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'material_needs',
        targetVariable: 'rate',
        expectedValue: 3.90,
        tolerance: 0.05,
        message: 'Introduce la Tasa de Uso de MP: 3.90 (la ves en el panel izquierdo).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'production_target',
        suggestionId: 'labor_needs',
        message: 'Vuelve al nodo de Producción y haz clic en "+ Calcular Horas Mano de Obra".',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'labor_needs',
        targetVariable: 'rate',
        expectedValue: 4.36,
        tolerance: 0.05,
        message: 'Introduce la Tasa MO: 4.36 (la ves en el panel izquierdo).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'material_needs',
        suggestionId: 'cost_material',
        message: 'En el nodo Req. Materia Prima, haz clic en "+ Calcular Costo Material".',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_material',
        targetVariable: 'price',
        expectedValue: 2.25,
        tolerance: 0.05,
        message: 'Introduce el Precio por Unidad de MP: $2.25 (del panel izquierdo).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'labor_needs',
        suggestionId: 'workforce',
        message: 'En Req. Mano de Obra, haz clic en "+ Calcular Fuerza Laboral".',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'workforce',
        targetVariable: 'hrs_per_worker',
        expectedValue: 500,
        tolerance: 0.01,
        message: 'Introduce las Horas por Trabajador: 500.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'workforce',
        suggestionId: 'cost_labor',
        message: 'Haz clic en "+ Calcular Costo Mano de Obra".',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_labor',
        targetVariable: 'workers',
        expectedValue: 1852,
        tolerance: 0.01,
        message: 'Introduce Total Trabajadores: 1,852 (del panel). Se paga a toda la plantilla.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_labor',
        targetVariable: 'wage',
        expectedValue: 2.30,
        tolerance: 0.05,
        message: 'Introduce el Salario por Hora: $2.30 (del panel izquierdo).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_labor',
        targetVariable: 'hours',
        expectedValue: 500,
        tolerance: 0.01,
        message: 'Introduce Horas/Trabajador: 500.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'cost_material',
        suggestionId: 'total_cost',
        message: 'En Costo Material, haz clic en "+ Añadir al Costo Total".',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'total_cost',
        targetVariable: 'fix_cost',
        expectedValue: 400000,
        tolerance: 0.01,
        message: 'Introduce los Costos Fijos: $400,000 (del panel izquierdo).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'total_cost',
        suggestionId: 'unit_cost',
        message: 'Haz clic en "+ Calcular Costo Unitario".',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'info',
        message: '🎉 ¡Escenario 1 completado! El Costo Unitario es ~$20.71. Ahora pasemos al Escenario 2.',
      },
    ],
  },
  {
    id: 2,
    title: 'Máxima Capacidad',
    enunciado: 'Ha llegado un pedido extraordinario. Debes producir al máximo de tu capacidad: 263,420 unidades. El reporte indica que tus trabajadores actuales no alcanzan a cubrir las horas necesarias. Calcula cuántas personas debes contratar bajo la Regla 2x y determina el impacto en el Costo Unitario.',
    color: 'bg-orange-500',
    accentColor: '#f97316',
    steps: [
      {
        targetType: 'fill-input',
        targetNodeType: 'production_target',
        targetVariable: 'target',
        expectedValue: 263420,
        tolerance: 0.01,
        message: 'Cambia las Unidades Objetivo a 263,420 (máxima capacidad).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'material_needs',
        targetVariable: 'rate',
        expectedValue: 3.90,
        tolerance: 0.05,
        message: 'Verifica que la Tasa MP sea 3.90.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'labor_needs',
        targetVariable: 'rate',
        expectedValue: 4.36,
        tolerance: 0.05,
        message: 'Verifica que la Tasa MO sea 4.36.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'click-suggestion',
        targetNodeType: 'workforce',
        suggestionId: 'hiring',
        message: 'En Fuerza Laboral, haz clic en "+ Decisión de Contratación".',
        highlightTarget: 'node-suggestion',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'hiring',
        targetVariable: 'current',
        expectedValue: 1852,
        tolerance: 0.01,
        message: 'Introduce la Fuerza Laboral Actual: 1,852 trabajadores.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'info',
        message: '📊 Déficit = 1,148,511 hrs - 926,000 hrs disponibles = 222,511 hrs. Nuevos contratados = (222,511/500)×2 ≈ 891.',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_labor',
        targetVariable: 'workers',
        expectedValue: 2743,
        tolerance: 0.02,
        message: 'Actualiza Total Trabajadores a 2,743 (1,852 + 891 nuevos).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_material',
        targetVariable: 'price',
        expectedValue: 2.25,
        tolerance: 0.05,
        message: 'Verifica que el Precio MP sea $2.25.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'total_cost',
        targetVariable: 'fix_cost',
        expectedValue: 400000,
        tolerance: 0.01,
        message: 'Verifica los Costos Fijos: $400,000.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'info',
        message: '🎉 ¡Escenario 2 completado! El Costo Unitario es ~$22.27. La Regla 2x encarece la producción. Pasemos al Escenario 3.',
      },
    ],
  },
  {
    id: 3,
    title: 'Crisis de Suministros',
    enunciado: 'Ante un entorno de alta inflación, planeas reducir la marcha a 180,000 unidades. Tu Stock Final de MP es de solo 400,000 unidades a precio viejo. El resto de la MP necesaria debe comprarse un 25% más cara. Calcula el Costo Total y el Costo Unitario usando la valoración de inventarios. Recuerda: se paga a TODOS los 1,852 trabajadores aunque no se usen todas sus horas.',
    color: 'bg-red-500',
    accentColor: '#ef4444',
    steps: [
      {
        targetType: 'fill-input',
        targetNodeType: 'production_target',
        targetVariable: 'target',
        expectedValue: 180000,
        tolerance: 0.01,
        message: 'Cambia las Unidades Objetivo a 180,000 (producción reducida).',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'material_needs',
        targetVariable: 'rate',
        expectedValue: 3.90,
        tolerance: 0.05,
        message: 'Verifica la Tasa MP: 3.90. Se necesitan 702,000 uds de MP.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'info',
        message: '📦 Dinámica de Inventario: Tienes 400,000 uds a $2.25 (precio viejo). Faltan 302,000 uds al precio nuevo ($2.25 × 1.25 = $2.8125).',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_material',
        targetVariable: 'units',
        expectedValue: 702000,
        tolerance: 0.01,
        message: 'En Costo Material, introduce las unidades totales de MP: 702,000.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_material',
        targetVariable: 'price',
        expectedValue: 2.4921,
        tolerance: 0.03,
        message: 'Introduce el precio ponderado: (400k×$2.25 + 302k×$2.8125)/702k ≈ $2.49. O calcula manualmente el valor total.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'info',
        message: '💡 Costo MP = $1,749,375. Esto combina el stock a precio viejo + compra a precio inflado.',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_labor',
        targetVariable: 'workers',
        expectedValue: 1852,
        tolerance: 0.01,
        message: '⚠️ COSTO HUNDIDO: Se paga a los 1,852 trabajadores completos aunque hay capacidad ociosa.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_labor',
        targetVariable: 'wage',
        expectedValue: 2.30,
        tolerance: 0.05,
        message: 'Salario por Hora: $2.30.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'cost_labor',
        targetVariable: 'hours',
        expectedValue: 500,
        tolerance: 0.01,
        message: 'Horas/Trabajador: 500. Costo MO = 1,852 × 500 × $2.30 = $2,129,800.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'fill-input',
        targetNodeType: 'total_cost',
        targetVariable: 'fix_cost',
        expectedValue: 400000,
        tolerance: 0.01,
        message: 'Costos Fijos: $400,000.',
        highlightTarget: 'node-input',
      },
      {
        targetType: 'info',
        message: '🎉 ¡Escenario 3 completado! Costo Unitario ≈ $23.77. Nota cómo la inflación y la capacidad ociosa encarecen la producción.',
      },
    ],
  },
];
