export interface DemoStep {
  targetType: 'load-report' | 'select-scenario' | 'fill-input' | 'click-suggestion' | 'info';
  targetNodeType?: string;
  targetVariable?: string;
  suggestionId?: string;
  expectedValue?: number;
  tolerance?: number; // fraction, e.g. 0.05 = 5%
  message: string;
  highlightTarget?: 'report-panel' | 'node-input' | 'node-suggestion' | 'scenario-card';
  scenarioCardIndex?: number;
}

export interface DemoScenario {
  id: number;
  title: string;
  enunciado: string;
  color: string; // tailwind bg class
  accentColor: string; // hex for pulse
  steps: DemoStep[];
}

/* ─── Escenario 1: Línea Base (210,000 uds) ─── */
const scenario1Steps: DemoStep[] = [
  {
    targetType: 'fill-input',
    targetNodeType: 'production_target',
    targetVariable: 'target',
    expectedValue: 210000,
    tolerance: 0.01,
    message: 'Escribe 210,000 en "Unidades Objetivo". Operaremos al 80% de capacidad.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'material_needs',
    message: 'Haz clic en "+ Calcular Materia Prima" para crear el nodo de requerimientos.',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'material_needs',
    targetVariable: 'rate',
    expectedValue: 3.90,
    tolerance: 0.05,
    message: 'Introduce la Tasa de Uso de MP: 3.90. Req. MP = 210,000 × 3.90 = 819,000 uds.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'labor_needs',
    message: 'Vuelve al nodo de Producción y haz clic en "+ Calcular Horas Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'labor_needs',
    targetVariable: 'rate',
    expectedValue: 4.36,
    tolerance: 0.05,
    message: 'Introduce la Tasa MO: 4.36. Req. MO = 210,000 × 4.36 = 915,600 hrs.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'material_needs',
    suggestionId: 'cost_material',
    message: 'En Req. Materia Prima, haz clic en "+ Calcular Costo Material".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'price',
    expectedValue: 2.25,
    tolerance: 0.05,
    message: 'Precio por Unidad de MP: $2.25. Costo MP = 819,000 × $2.25 = $1,842,750.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'labor_needs',
    suggestionId: 'workforce',
    message: 'En Req. Mano de Obra, haz clic en "+ Calcular Fuerza Laboral".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'workforce',
    targetVariable: 'hrs_per_worker',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Introduce Hrs/Trabajador: 500.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '📊 Resultado: 915,600 / 500 = 1,831.2 trabajadores necesarios. Pero tienes 1,852. Tú decides: ¿despides a los que sobran o pagas a todos?',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'cost_labor',
    message: 'Haz clic en "+ Calcular Costo Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'workers',
    expectedValue: 1852,
    tolerance: 0.02,
    message: 'Total Trabajadores: escribe 1,852 (o 1,831 si decides despedir). Ambos valores son válidos.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'wage',
    expectedValue: 2.30,
    tolerance: 0.05,
    message: 'Salario por Hora: $2.30.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'hours',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Horas/Trabajador: 500. Costo MO = Trabajadores × 500 × $2.30.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'cost_material',
    suggestionId: 'total_cost',
    message: 'En Costo Material, haz clic en "+ Añadir al Costo Total".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'total_cost',
    targetVariable: 'fix_cost',
    expectedValue: 400000,
    tolerance: 0.01,
    message: 'Costos Fijos: $400,000.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'total_cost',
    suggestionId: 'unit_cost',
    message: 'Haz clic en "+ Calcular Costo Unitario".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'info',
    message: '🎉 ¡Escenario 1 completado! Costo Unitario ≈ $20.71. Pasemos al Escenario 2.',
  },
];

/* ─── Escenario 2: Máxima Capacidad (263,420 uds) ─── */
const scenario2Steps: DemoStep[] = [
  {
    targetType: 'fill-input',
    targetNodeType: 'production_target',
    targetVariable: 'target',
    expectedValue: 263420,
    tolerance: 0.01,
    message: 'Escribe 263,420 en "Unidades Objetivo" (máxima capacidad).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'material_needs',
    message: 'Haz clic en "+ Calcular Materia Prima".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'material_needs',
    targetVariable: 'rate',
    expectedValue: 3.90,
    tolerance: 0.05,
    message: 'Tasa de Uso MP: 3.90. Req. MP = 263,420 × 3.90 = 1,027,338 uds.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'labor_needs',
    message: 'Haz clic en "+ Calcular Horas Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'labor_needs',
    targetVariable: 'rate',
    expectedValue: 4.36,
    tolerance: 0.05,
    message: 'Tasa MO: 4.36. Req. MO = 263,420 × 4.36 = 1,148,511 hrs.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'labor_needs',
    suggestionId: 'workforce',
    message: 'Haz clic en "+ Calcular Fuerza Laboral".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'workforce',
    targetVariable: 'hrs_per_worker',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Hrs/Trabajador: 500. Necesitas 1,148,511 / 500 = 2,297 trabajadores.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '⚠️ Necesitas 2,297 trabajadores pero solo tienes 1,852. ¡Déficit enorme! Hay que contratar.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'hiring',
    message: 'Haz clic en "+ Decisión de Contratación".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'hiring',
    targetVariable: 'current',
    expectedValue: 1852,
    tolerance: 0.01,
    message: 'Fuerza Laboral Actual: 1,852 trabajadores.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '📊 Regla 2x: Nuevos = (2,297 − 1,852) × 2 = 891. Total nómina = 1,852 + 891 = 2,743.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'cost_labor',
    message: 'Haz clic en "+ Calcular Costo Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'workers',
    expectedValue: 2743,
    tolerance: 0.02,
    message: 'Total Trabajadores: 2,743 (1,852 + 891 nuevos).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'wage',
    expectedValue: 2.30,
    tolerance: 0.05,
    message: 'Salario por Hora: $2.30.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'hours',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Horas/Trabajador: 500. Costo MO = 2,743 × 500 × $2.30 = $3,154,450.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'material_needs',
    suggestionId: 'cost_material',
    message: 'En Req. Materia Prima, haz clic en "+ Calcular Costo Material".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'price',
    expectedValue: 2.25,
    tolerance: 0.05,
    message: 'Precio MP: $2.25. Costo MP = 1,027,338 × $2.25 = $2,311,510.50.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'cost_material',
    suggestionId: 'total_cost',
    message: 'En Costo Material, haz clic en "+ Añadir al Costo Total".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'total_cost',
    targetVariable: 'fix_cost',
    expectedValue: 400000,
    tolerance: 0.01,
    message: 'Costos Fijos: $400,000.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'total_cost',
    suggestionId: 'unit_cost',
    message: 'Haz clic en "+ Calcular Costo Unitario".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'info',
    message: '🎉 ¡Escenario 2 completado! Costo Unitario ≈ $22.27. La Regla 2x encarece la producción. Pasemos al Escenario 3.',
  },
];

/* ─── Escenario 3: Crisis de Suministros (180,000 uds) ─── */
const scenario3Steps: DemoStep[] = [
  {
    targetType: 'fill-input',
    targetNodeType: 'production_target',
    targetVariable: 'target',
    expectedValue: 180000,
    tolerance: 0.01,
    message: 'Escribe 180,000 en "Unidades Objetivo" (producción reducida por inflación).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'material_needs',
    message: 'Haz clic en "+ Calcular Materia Prima".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'material_needs',
    targetVariable: 'rate',
    expectedValue: 3.90,
    tolerance: 0.05,
    message: 'Tasa MP: 3.90. Req. MP = 180,000 × 3.90 = 702,000 uds.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '📦 Dinámica de Inventario: Tienes 400,000 uds a $2.25 (precio viejo). Faltan 302,000 uds al precio nuevo ($2.25 × 1.25 = $2.8125).',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'material_needs',
    suggestionId: 'cost_material',
    message: 'Haz clic en "+ Calcular Costo Material".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'units',
    expectedValue: 702000,
    tolerance: 0.01,
    message: 'Total Unidades MP: 702,000.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'price',
    expectedValue: 2.4921,
    tolerance: 0.03,
    message: 'Precio ponderado: (400k × $2.25 + 302k × $2.8125) / 702k ≈ $2.49.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '💡 Costo MP = $1,749,375. Combina stock a precio viejo + compra a precio inflado.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'labor_needs',
    message: 'Haz clic en "+ Calcular Horas Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'labor_needs',
    targetVariable: 'rate',
    expectedValue: 4.36,
    tolerance: 0.05,
    message: 'Tasa MO: 4.36. Req. MO = 180,000 × 4.36 = 784,800 hrs.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'labor_needs',
    suggestionId: 'workforce',
    message: 'Haz clic en "+ Calcular Fuerza Laboral".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'workforce',
    targetVariable: 'hrs_per_worker',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Hrs/Trabajador: 500. Solo necesitas 784,800 / 500 = 1,569.6 trabajadores.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '⚠️ COSTO HUNDIDO: Solo necesitas 1,569.6 trabajadores pero pagas a los 1,852 completos. Hay capacidad ociosa.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'cost_labor',
    message: 'Haz clic en "+ Calcular Costo Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'workers',
    expectedValue: 1852,
    tolerance: 0.01,
    message: 'Total Trabajadores: 1,852 (se paga a toda la plantilla).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'wage',
    expectedValue: 2.30,
    tolerance: 0.05,
    message: 'Salario por Hora: $2.30.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'hours',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Horas/Trabajador: 500. Costo MO = 1,852 × 500 × $2.30 = $2,129,800.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'cost_material',
    suggestionId: 'total_cost',
    message: 'En Costo Material, haz clic en "+ Añadir al Costo Total".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'total_cost',
    targetVariable: 'fix_cost',
    expectedValue: 400000,
    tolerance: 0.01,
    message: 'Costos Fijos: $400,000.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'total_cost',
    suggestionId: 'unit_cost',
    message: 'Haz clic en "+ Calcular Costo Unitario".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'info',
    message: '🎉 ¡Escenario 3 completado! Costo Unitario ≈ $23.77. La inflación y la capacidad ociosa encarecen la producción.',
  },
];

/* ─── Export ─── */
export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 1,
    title: 'Operación Óptima',
    enunciado: 'La empresa busca optimizar su producción. Con una capacidad de 263,420 unidades, se ha decidido operar al 80% de capacidad (aprox. 210,000 unidades). Calcula el Costo Total de Producción y el Costo Unitario bajo estas condiciones.',
    color: 'bg-emerald-500',
    accentColor: '#10b981',
    steps: scenario1Steps,
  },
  {
    id: 2,
    title: 'Máxima Capacidad',
    enunciado: 'Ha llegado un pedido extraordinario. Debes producir al máximo de tu capacidad: 263,420 unidades. El reporte indica que tus trabajadores actuales no alcanzan a cubrir las horas necesarias. Calcula cuántas personas debes contratar bajo la Regla 2x y determina el impacto en el Costo Unitario.',
    color: 'bg-orange-500',
    accentColor: '#f97316',
    steps: scenario2Steps,
  },
  {
    id: 3,
    title: 'Crisis de Suministros',
    enunciado: 'Ante un entorno de alta inflación, planeas reducir la marcha a 180,000 unidades. Tu Stock Final de MP es de solo 400,000 unidades a precio viejo. El resto de la MP necesaria debe comprarse un 25% más cara. Calcula el Costo Total y el Costo Unitario usando la valoración de inventarios. Recuerda: se paga a TODOS los 1,852 trabajadores aunque no se usen todas sus horas.',
    color: 'bg-red-500',
    accentColor: '#ef4444',
    steps: scenario3Steps,
  },
];
