export interface DemoStep {
  targetType: 'load-report' | 'select-scenario' | 'fill-input' | 'click-suggestion' | 'info';
  targetNodeType?: string;
  targetVariable?: string;
  suggestionId?: string;
  expectedValue?: number;
  tolerance?: number; // fraction, e.g. 0.05 = 5%
  message: string;
  highlightTarget?: 'report-panel' | 'node-input' | 'node-suggestion' | 'scenario-card';
  scenarioCardIndex?: number;
}

export interface DemoScenario {
  id: number;
  title: string;
  enunciado: string;
  color: string; // tailwind bg class
  accentColor: string; // hex for pulse
  steps: DemoStep[];
}

/* ─── Escenario 1: Línea Base (210,000 uds) ─── */
const scenario1Steps: DemoStep[] = [
  {
    targetType: 'fill-input',
    targetNodeType: 'production_target',
    targetVariable: 'target',
    expectedValue: 210000,
    tolerance: 0.01,
    message: 'Calcula las "Unidades Objetivo". Según el enunciado, operamos al 80% de la capacidad de planta. Consulta la capacidad en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'material_needs',
    message: 'Haz clic en "+ Calcular Materia Prima" para crear el nodo de requerimientos.',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'material_needs',
    targetVariable: 'rate',
    expectedValue: 3.90,
    tolerance: 0.05,
    message: 'Introduce la Tasa de Uso de MP. Puedes encontrarla en el panel de reporte del trimestre anterior.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'labor_needs',
    message: 'Vuelve al nodo de Producción y haz clic en "+ Calcular Horas Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'labor_needs',
    targetVariable: 'rate',
    expectedValue: 4.36,
    tolerance: 0.05,
    message: 'Introduce la Tasa de Mano de Obra. Consúltala en el panel de reporte del trimestre anterior.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'material_needs',
    suggestionId: 'cost_material',
    message: 'En Req. Materia Prima, haz clic en "+ Calcular Costo Material".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'price',
    expectedValue: 2.25,
    tolerance: 0.05,
    message: 'Introduce el Precio por Unidad de MP. Revísalo en la sección de inventario del panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'labor_needs',
    suggestionId: 'workforce',
    message: 'En Req. Mano de Obra, haz clic en "+ Calcular Fuerza Laboral".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'workforce',
    targetVariable: 'hrs_per_worker',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Introduce las Horas por Trabajador. Consúltalo en la sección de productividad del panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '📊 Calcula cuántos trabajadores necesitas dividiendo las horas totales entre las horas por trabajador. Compara con la plantilla actual (panel de reporte). ¿Sobran o faltan? Tú decides qué hacer.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'cost_labor',
    message: 'Haz clic en "+ Calcular Costo Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'workers',
    expectedValue: 1852,
    tolerance: 0.02,
    message: 'Introduce el Total de Trabajadores. Puedes pagar a toda la plantilla o solo a los necesarios. Tú decides.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'wage',
    expectedValue: 2.30,
    tolerance: 0.05,
    message: 'Introduce el Salario por Hora. Consúltalo en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'hours',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Introduce las Horas por Trabajador (mismo dato de productividad del reporte).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'cost_material',
    suggestionId: 'total_cost',
    message: 'En Costo Material, haz clic en "+ Añadir al Costo Total".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'total_cost',
    targetVariable: 'fix_cost',
    expectedValue: 400000,
    tolerance: 0.01,
    message: 'Introduce los Costos Fijos. Encuéntralos en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'total_cost',
    suggestionId: 'unit_cost',
    message: 'Haz clic en "+ Calcular Costo Unitario".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'info',
    message: '🎉 ¡Escenario 1 completado! Revisa tu Costo Unitario. Pasemos al Escenario 2.',
  },
];

/* ─── Escenario 2: Máxima Capacidad (263,420 uds) ─── */
const scenario2Steps: DemoStep[] = [
  {
    targetType: 'fill-input',
    targetNodeType: 'production_target',
    targetVariable: 'target',
    expectedValue: 263420,
    tolerance: 0.01,
    message: 'Introduce las "Unidades Objetivo". En este escenario operamos a máxima capacidad. Consulta el dato en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'material_needs',
    message: 'Haz clic en "+ Calcular Materia Prima".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'material_needs',
    targetVariable: 'rate',
    expectedValue: 3.90,
    tolerance: 0.05,
    message: 'Introduce la Tasa de Uso de MP. Consúltala en el panel de reporte del trimestre anterior.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'labor_needs',
    message: 'Haz clic en "+ Calcular Horas Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'labor_needs',
    targetVariable: 'rate',
    expectedValue: 4.36,
    tolerance: 0.05,
    message: 'Introduce la Tasa de Mano de Obra. Consúltala en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'labor_needs',
    suggestionId: 'workforce',
    message: 'Haz clic en "+ Calcular Fuerza Laboral".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'workforce',
    targetVariable: 'hrs_per_worker',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Introduce las Horas por Trabajador. Consúltalo en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '⚠️ Compara los trabajadores necesarios con la plantilla actual (panel de reporte). ¿Alcanza? Si hay déficit, necesitarás contratar.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'hiring',
    message: 'Haz clic en "+ Decisión de Contratación".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'hiring',
    targetVariable: 'current',
    expectedValue: 1852,
    tolerance: 0.01,
    message: 'Introduce la Fuerza Laboral Actual. Encuéntrala en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '📊 Aplica la Regla 2x: los nuevos contratados son el doble del déficit. Calcula el total de nómina sumando actuales + nuevos.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'cost_labor',
    message: 'Haz clic en "+ Calcular Costo Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'workers',
    expectedValue: 2743,
    tolerance: 0.02,
    message: 'Introduce el Total de Trabajadores. Recuerda sumar los actuales más los nuevos contratados (Regla 2x).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'wage',
    expectedValue: 2.30,
    tolerance: 0.05,
    message: 'Introduce el Salario por Hora. Consúltalo en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'hours',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Introduce las Horas por Trabajador (mismo dato de productividad del reporte).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'material_needs',
    suggestionId: 'cost_material',
    message: 'En Req. Materia Prima, haz clic en "+ Calcular Costo Material".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'price',
    expectedValue: 2.25,
    tolerance: 0.05,
    message: 'Introduce el Precio por Unidad de MP. Revísalo en la sección de inventario del panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'cost_material',
    suggestionId: 'total_cost',
    message: 'En Costo Material, haz clic en "+ Añadir al Costo Total".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'total_cost',
    targetVariable: 'fix_cost',
    expectedValue: 400000,
    tolerance: 0.01,
    message: 'Introduce los Costos Fijos. Encuéntralos en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'total_cost',
    suggestionId: 'unit_cost',
    message: 'Haz clic en "+ Calcular Costo Unitario".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'info',
    message: '🎉 ¡Escenario 2 completado! Compara tu Costo Unitario con el del Escenario 1. ¿Cuánto impacta la Regla 2x? Pasemos al Escenario 3.',
  },
];

/* ─── Escenario 3: Crisis de Suministros (180,000 uds) ─── */
const scenario3Steps: DemoStep[] = [
  {
    targetType: 'fill-input',
    targetNodeType: 'production_target',
    targetVariable: 'target',
    expectedValue: 180000,
    tolerance: 0.01,
    message: 'Introduce las "Unidades Objetivo". El enunciado indica una producción reducida por inflación. Lee el escenario para encontrar el dato.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'material_needs',
    message: 'Haz clic en "+ Calcular Materia Prima".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'material_needs',
    targetVariable: 'rate',
    expectedValue: 3.90,
    tolerance: 0.05,
    message: 'Introduce la Tasa de Uso de MP. Consúltala en el panel de reporte del trimestre anterior.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '📦 Dinámica de Inventario: Tienes stock a precio viejo (panel de reporte). El resto de la MP necesaria debe comprarse con el incremento del 25%. Calcula el precio ponderado.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'material_needs',
    suggestionId: 'cost_material',
    message: 'Haz clic en "+ Calcular Costo Material".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'units',
    expectedValue: 702000,
    tolerance: 0.01,
    message: 'Introduce el Total de Unidades de MP. Es el resultado de multiplicar las unidades objetivo por la tasa de uso.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_material',
    targetVariable: 'price',
    expectedValue: 2.4921,
    tolerance: 0.03,
    message: 'Calcula el Precio Ponderado de MP. Combina el stock a precio viejo y la compra nueva al precio inflado (+25%). Usa la fórmula de promedio ponderado.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '💡 Verifica tu cálculo: el precio ponderado combina inventario existente y compras nuevas. Revisa las cantidades de stock en el panel de reporte.',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'production_target',
    suggestionId: 'labor_needs',
    message: 'Haz clic en "+ Calcular Horas Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'labor_needs',
    targetVariable: 'rate',
    expectedValue: 4.36,
    tolerance: 0.05,
    message: 'Introduce la Tasa de Mano de Obra. Consúltala en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'labor_needs',
    suggestionId: 'workforce',
    message: 'Haz clic en "+ Calcular Fuerza Laboral".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'workforce',
    targetVariable: 'hrs_per_worker',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Introduce las Horas por Trabajador. Consúltalo en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'info',
    message: '⚠️ Compara los trabajadores necesarios con la plantilla actual. Hay capacidad ociosa. El enunciado indica que se paga a TODOS los trabajadores. ¿Mantienes la plantilla completa o decides diferente?',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'workforce',
    suggestionId: 'cost_labor',
    message: 'Haz clic en "+ Calcular Costo Mano de Obra".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'workers',
    expectedValue: 1852,
    tolerance: 0.10,
    message: 'Introduce el Total de Trabajadores. ¿Pagas a toda la plantilla o solo a los necesarios? Tú decides.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'wage',
    expectedValue: 2.30,
    tolerance: 0.05,
    message: 'Introduce el Salario por Hora. Consúltalo en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'cost_labor',
    targetVariable: 'hours',
    expectedValue: 500,
    tolerance: 0.01,
    message: 'Introduce las Horas por Trabajador (mismo dato de productividad del reporte).',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'cost_material',
    suggestionId: 'total_cost',
    message: 'En Costo Material, haz clic en "+ Añadir al Costo Total".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'fill-input',
    targetNodeType: 'total_cost',
    targetVariable: 'fix_cost',
    expectedValue: 400000,
    tolerance: 0.01,
    message: 'Introduce los Costos Fijos. Encuéntralos en el panel de reporte.',
    highlightTarget: 'node-input',
  },
  {
    targetType: 'click-suggestion',
    targetNodeType: 'total_cost',
    suggestionId: 'unit_cost',
    message: 'Haz clic en "+ Calcular Costo Unitario".',
    highlightTarget: 'node-suggestion',
  },
  {
    targetType: 'info',
    message: '🎉 ¡Escenario 3 completado! Compara tu Costo Unitario con los escenarios anteriores. ¿Cómo impactan la inflación y la capacidad ociosa?',
  },
];

/* ─── Export ─── */
export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 1,
    title: 'Operación Óptima',
    enunciado: 'La empresa busca optimizar su producción. Con una capacidad de 263,420 unidades, se ha decidido operar al 80% de capacidad (aprox. 210,000 unidades). Calcula el Costo Total de Producción y el Costo Unitario bajo estas condiciones.',
    color: 'bg-emerald-500',
    accentColor: '#10b981',
    steps: scenario1Steps,
  },
  {
    id: 2,
    title: 'Máxima Capacidad',
    enunciado: 'Ha llegado un pedido extraordinario. Debes producir al máximo de tu capacidad: 263,420 unidades. El reporte indica que tus trabajadores actuales no alcanzan a cubrir las horas necesarias. Calcula cuántas personas debes contratar bajo la Regla 2x y determina el impacto en el Costo Unitario.',
    color: 'bg-orange-500',
    accentColor: '#f97316',
    steps: scenario2Steps,
  },
  {
    id: 3,
    title: 'Crisis de Suministros',
    enunciado: 'Ante un entorno de alta inflación, planeas reducir la marcha a 180,000 unidades. Tu Stock Final de MP es de solo 400,000 unidades a precio viejo. El resto de la MP necesaria debe comprarse un 25% más cara. Calcula el Costo Total y el Costo Unitario usando la valoración de inventarios. Recuerda: se paga a TODOS los 1,852 trabajadores aunque no se usen todas sus horas.',
    color: 'bg-red-500',
    accentColor: '#ef4444',
    steps: scenario3Steps,
  },
];
